### ISSUE TITLE
reference.txt not found error

### ISSUE THREAD

**Issue by ItzSHIV** [athrvvvv/AppOpener#6]
reference.txt file not found error after importing and converting the python file to exe file

**Comment by athrvvvv** [comment]
@ItzSHIV  Please provide context. Tell me more, about what application and which **converting method** is used?

**Comment by sophiedavidson** [comment]
I have experienced a similar issue when converting a python file to .exe using PyInstaller. This issue prevents me from launching the .exe file. 

Error Message: FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\sophi\\AppData\\Local\\Temp\\_MEI264762\\AppOpener\\reference.txt'

**Comment by athrvvvv** [comment]
> I have experienced a similar issue when converting a python file to .exe using PyInstaller. This issue prevents me from launching the .exe file.
> 
> Error Message: FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\sophi\AppData\Local\Temp\_MEI264762\AppOpener\reference.txt'

Okay fixing this issue, tonight!

**Comment by athrvvvv** [comment]
@merksk8 can you look into this??

**Comment by AwitaGames** [comment]
Hello,

the problem is this:

```
Traceback (most recent call last):
  File "appopener_test.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "AppOpener\__init__.py", line 4, in <module>
  File "AppOpener\check.py", line 53, in check_reference
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Merk\\AppData\\Local\\Temp\\_MEI346282\\AppOpener\\reference.txt'
```

When creating an exe file, using ` main_path = os.path.dirname(__file__)` to get the path to the folder of the exe file doesn't seems to work.

**The solution is to get it like this:**

```
if getattr(sys, 'frozen', False):
    main_path = os.path.dirname(sys.executable)
elif __file__:
    main_path = os.path.dirname(__file__)
```

**I would recommend to make a function to get the main_path instead using this if-else everywhere it's used**( check.py, update_list.py, __init__.py, probably others) so if there's a problem with it we can modify easier in the future.

Please double check the solution, and I'm sorry but I don't have too much time this week to create the pull request and do more checkings.

Cheers!

**Comment by merksk8** [comment]
Hello,

the problem is this:

```
Traceback (most recent call last):
  File "appopener_test.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "AppOpener\__init__.py", line 4, in <module>
  File "AppOpener\check.py", line 53, in check_reference
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Merk\\AppData\\Local\\Temp\\_MEI346282\\AppOpener\\reference.txt'
```

When creating an exe file, using ` main_path = os.path.dirname(__file__)` to get the path to the folder of the exe file doesn't seems to work.

**The solution is to get it like this:**

```
if getattr(sys, 'frozen', False):
    main_path = os.path.dirname(sys.executable)
elif __file__:
    main_path = os.path.dirname(__file__)
```

**I would recommend to make a function to get the main_path instead using this if-else everywhere it's used**( check.py, update_list.py, __init__.py, probably others) so if there's a problem with it we can modify easier in the future.

Please double check the solution, and I'm sorry but I don't have too much time this week to create the pull request and do more checkings.

PD: sorry for the double notification, posted with the wrong account 🤣

EDIT: And please, next time provide more information so we can all find a solution faster. It takes no time to give some details and it helps a lot to find and fix the bugs faster, not only for this library but for any other one! :)

Cheers!

**Comment by ItzSHIV** [comment]
i have only one file which i want to convert which is main.py so what solution should i use ?
should i create a function in main.py file and give it the location of the exe file?

**Comment by merksk8** [comment]
> i have only one file which i want to convert which is main.py so what solution should i use ? should i create a function in main.py file and give it the location of the exe file?

I don't think you can change it on your end, the library needs to be updated because this runs when the library is initialized and also it's a local variable.

Let's see if @athrvvvv can apply this solution, i will try to make some time to make a pull request this afternoon if he's busy.

Cheers

**Comment by athrvvvv** [comment]
> i have only one file which i want to convert which is main.py so what solution should i use ? should i create a function in main.py file and give it the location of the exe file?

Yo bro! rolling AppOpener v1.4 today to fix #7 and #6

**Comment by ItzSHIV** [comment]
> > i have only one file which i want to convert which is main.py so what solution should i use ? should i create a function in main.py file and give it the location of the exe file?
> 
> Yo bro! rolling AppOpener v1.4 today to fix #7 and #6

thanks a bunch can i message u anywhere i want to get in touch with u if possible could u provide ur insta handle ?

**Comment by athrvvvv** [comment]
Hey bruhhhh, its been a while since you rised this issue...
**AppOpener version 1.4 rolls today**, with the release of it this issue might have been fixed. You may close this issue now if your problem is solved 🤗

**Install AppOpener v1.4**

```
pip install AppOpener==1.4
```

---

### Converting to standalone file (EXE) 

Follow any Example from [here](https://github.com/athrvvvv/AppOpener/tree/v1.4/Examples).

```
pyinstaller -F Tkinter.py --hidden-import AppOpener --exclude-module _bootlocale
```

If you had any problem, Iam always here bruhhhhh


> 
> thanks a bunch can i message u anywhere i want to get in touch with u if possible could u provide ur insta handle ?


Tip:  Real programmers prefer Discord to interact 

### Stay connected 🤝

- [Mail](mailto:athrvchaulkar@gmail.com)
- [Twitter](https://twitter.com/athrvvvvv)
- [YouTube](https://www.youtube.com/c/ACUNBOXING2017)
- Discord athrv#3777

**Comment by ItzSHIV** [comment]
> 

yes thanks a ton

**Comment by ITSME1516** [comment]
hello

**Comment by ITSME1516** [comment]
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\aadhi\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\AppOpener\\Data\\reference.txt'

IAM NOT ABBLE TO IMPORT APPOPENER
