### ISSUE TITLE
Need to install `pywin32` to get working on Windows 10

### ISSUE THREAD

**Issue by iansedano** [athrvvvv/AppOpener#7]
I ran into an error after installing with `pip` saying that it couldn't find `win32gui`. I'm on Windows 10.

Trying to install `win32gui` gives you a different error, so I tried installine `pywin32` and that seems to have done the trick.

**Comment by athrvvvv** [comment]
@iansedano Hello there, 
AppOpener do require **win32gui** for several operations. 

To counter this issue follow follwowing things:

1. ```pip uninstall AppOpener```

2. ```pip install pywin32```

3. ```pip install AppOpener```

Also do visit, 
- Official documentation - https://AppOpener.readthedocs.io/en/latest/

If your issue is solved, you may close this issue 🤗

cheers, athrv.

**Comment by iansedano** [comment]
Right, thanks for the prompt response, I managed to find the fix as I mentioned in the original comment, but not in the documentation.

I thought by linking the docs in your comment that I might have missed it, but I checked again and can't seem to find it. Apologies if it's right in front of me, but the only instructions I see are:

```
pip install AppOpener
```

If you like I can see about making a PR to add a note to the docs and/or README to say to Windows users that they'll first need to install `pywin32`.

Alternatively, I could look into including it as a dependency on Windows in the build spec.

**Comment by athrvvvv** [comment]
To any open-source project successful and efficient, one requires to observe mistakes and find a way to fix it. You are doing absolutely great job!
It would be great to take **AppOpener** to the next level together 🤝
Go ahead make a PR, to counter this issue 🤗

**Comment by athrvvvv** [comment]
Hey there,
**AppOpener version 1.4 rolls today**, with the release of it this issue might have been fixed. You may close this issue now if your problem is cleared. 

**Install AppOpener v1.4**

```
pip install AppOpener==1.4
```

Also I came to know, you work for @realpython, if you write article on AppOpener Iam totally fine with it (sarcasm). Haha

**Comment by iansedano** [comment]
Oh, nice. You've already included the dependency for Windows, nice, it works from scratch for me now 🎉
